install_nginx_ingress_controller: |
  #!/bin/bash
  helm repo update
  helm install stable/nginx-ingress --namespace kube-system --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false

install_kubelego_controller: |
  #!/bin/bash
  helm install stable/kube-lego --set config.LEGO_EMAIL={{ az_email_lego }} --set config.LEGO_URL=https://acme-v01.api.letsencrypt.org/directory
