- name: Login to the AKS service
  shell: az aks get-credentials --resource-group {{ az_resource_group }} --name {{ az_aks_cluster }}
  args:
    chdir: /home/{{ ansible_ssh_user }}
    executable: /bin/bash
- template:
    src: azure-deployment-aks.yml.j2
    dest: /home/{{ ansible_ssh_user }}/azure-deployment-aks.yml
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
#    mode: '0600'
- name: Execute AKS deployment script
  shell: kubectl create -f azure-deployment-aks.yml
  args:
    chdir: /home/{{ ansible_ssh_user }}
    executable: /bin/bash