- hosts: Name_ap-nginx-vm
  gather_facts: false
  remote_user: "{{ ansible_ssh_user }}"
  become: yes
  vars_files:
      - ../../group_vars/all/main.yml
  
  pre_tasks:
    - debug:
        msg: "Start playing in target server"

  roles:
    - role: brentwg.azure-cli
      tags: azure-cli
    - role: geerlingguy.pip
      tags: pip
    - role: githubixx.kubectl
      tags: kubectl
    - role: app.machine
      tags: install_packages