- hosts: local
  gather_facts: false
  remote_user: vagrant
  become: yes
  vars_files:
      - ../../group_vars/all/main.yml
  
  pre_tasks:
    - debug:
        msg: "Start playing in target server"

  roles:
    - role: brentwg.azure-cli
      tags: azure-cli
    - role: geerlingguy.pip
      tags: pip
    - role: githubixx.kubectl
      tags: kubectl