- hosts: local
  gather_facts: True
  remote_user: vagrant
  become: no
  vars_files:
      - ../../group_vars/all/main.yml
  
  pre_tasks:
    - debug:
        msg: "Start playing in target server"

  roles:
    - role: brentwg.azure-cli
      become: yes
      tags: azure-cli
    - role: geerlingguy.pip
      tags: pip